name: Portfolio Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *" # daily at 17:00 UTC

# allow workflow to push commits
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./PortfolioAutomation/PortfolioAutomation.sln

      - name: Build solution
        run: dotnet build ./PortfolioAutomation/PortfolioAutomation.sln --configuration Release --no-restore

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: |
          dotnet test ./PortfolioAutomationTest/PortfolioAutomationTest.csproj \
            --logger "trx;LogFileName=test-results.trx" \
            --results-directory ./TestResults
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        continue-on-error: true   

      - name: Convert TRX to JSON
        if: always()
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          export PATH="$PATH:/home/runner/.dotnet/tools"

          # generate JSON summary from trx
          reportgenerator -reports:./TestResults/test-results.trx \
                          -targetdir:./TestResults/json \
                          -reporttypes:Json

          # rename output for consistency
          cp ./TestResults/json/Summary.json ./TestResults/test-results.json

      - name: Upload test results (TRX + JSON)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults/*

      - name: Commit JSON results to results branch
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          mkdir -p results
          cp ./TestResults/test-results.json results/$(date +'%Y-%m-%d').json

          git fetch origin
          git checkout results || git checkout -b results

          git add results/
          git commit -m "Add test results for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin results
