name: Portfolio Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./PortfolioAutomation/PortfolioAutomation.sln

      - name: Build solution
        run: dotnet build ./PortfolioAutomation/PortfolioAutomation.sln --configuration Release --no-restore

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: dotnet test ./PortfolioAutomationTest/PortfolioAutomationTest.csproj --logger "trx;LogFileName=test-results.trx" --results-directory ./TestResults
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        continue-on-error: true   

      - name: Upload test results
        if: always()             
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults/*.trx

      - name: Post Set up .NET
        if: always()             
        run: echo "Post test cleanup completed."
