name: Portfolio Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore PortfolioAutomation.sln

      - name: Build solution
        run: dotnet build PortfolioAutomation.sln --configuration Release --no-restore

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: dotnet test PortfolioAutomation.sln --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"
        env:
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults/*.trx'
